# Prompt
force_color_prompt=yes
color_prompt=yes
PS1=$'\uf0a9 '
PS1="\[\e]0;\w\a\]$PS1"

# History
HISTSIZE=32768
HISTFILESIZE=32768
HISTCONTROL=ignoreboth
shopt -s histappend

# File system
shopt -s cdspell
shopt -s autocd

# PATH
set +h
if [ -d "$HOME/bin" ]; then
  PATH="$HOME/bin:$PATH"
fi

if [ -d "$HOME/local/bin" ]; then
  PATH="$HOME/.local/bin:$PATH"
fi

# Aliases
for FILE in "$HOME"/.*aliases; do
  . "$FILE"
done

# Autocompletion
. /usr/share/bash-completion/bash_completion

# Init Mise
if command -v mise &> /dev/null; then
  eval "$(mise activate bash)"
fi
