# Unique PATH
typeset -U path

# Local BIN
[[ -d "$HOME/.local/bin" ]] && path=("$HOME/.local/bin" $path)
[[ -d "$HOME/bin" ]]        && path=("$HOME/bin" $path)

# Export PATH
export PATH

# Init Mise
if command -v mise &>/dev/null; then
  eval "$(mise activate zsh --shims)"
fi
