# Init Oh-My-Zsh
if [[ -d "$HOME/.oh-my-zsh" ]]; then
  export ZSH="$HOME/.oh-my-zsh"
  ZSH_THEME="robbyrussell"
  
  plugins=(
    git
    docker
    docker-compose
    mise
    golang
    zsh-completions
    zsh-autosuggestions
    zsh-history-substring-search
    zsh-syntax-highlighting
  )

  source "$ZSH/oh-my-zsh.sh"
fi

# Init Aliases (The (N) qualifier handles missing files gracefully)
for FILE in "$HOME"/.*aliases(N); do
  source "$FILE"
done
