# PATH
if [ -d "$HOME/bin" ]; then
  PATH="$HOME/bin:$PATH"
fi

if [ -d "$HOME/local/bin" ]; then
  PATH="$HOME/.local/bin:$PATH"
fi

# Aliases
for FILE in "$HOME"/.*aliases(N); do
  . "$FILE"
done

# Init Oh-My-Zsh
if [ -d "$HOME/.oh-my-zsh" ]; then
  ZSH="$HOME/.oh-my-zsh"
  ZSH_THEME="robbyrussell"
  plugins=(git docker docker-compose mise golang zsh-completions zsh-autosuggestions zsh-syntax-highlighting zsh-history-substring-search)
  . "$ZSH/oh-my-zsh.sh"
fi
